[2025-10-10T23:27:29.281+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [queued]>
[2025-10-10T23:27:29.283+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [queued]>
[2025-10-10T23:27:29.283+0200] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2025-10-10T23:27:29.288+0200] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): send_batch_predictions> on 2025-10-10 21:18:00+00:00
[2025-10-10T23:27:29.291+0200] {standard_task_runner.py:60} INFO - Started process 41415 to run task
[2025-10-10T23:27:29.293+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'predict_batch_dag', 'send_batch_predictions', 'scheduled__2025-10-10T21:18:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/var/folders/rp/syznybx160jd0kg9k7r_sj8w0000gn/T/tmpza634pb8']
[2025-10-10T23:27:29.294+0200] {standard_task_runner.py:88} INFO - Job 100: Subtask send_batch_predictions
[2025-10-10T23:27:29.312+0200] {task_command.py:423} INFO - Running <TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [running]> on host ebots-macbook-pro.local
[2025-10-10T23:27:29.334+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='predict_batch_dag' AIRFLOW_CTX_TASK_ID='send_batch_predictions' AIRFLOW_CTX_EXECUTION_DATE='2025-10-10T21:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-10T21:18:00+00:00'
[2025-10-10T23:27:29.335+0200] {logging_mixin.py:188} INFO - ðŸ“„ Found CSV file: /Users/ebotfabien/Desktop/school/air_new/dags/destination/data_part_1.csv
[2025-10-10T23:27:29.340+0200] {logging_mixin.py:188} INFO - ðŸ“¦ Sending 10 batch(es)...
[2025-10-10T23:28:39.802+0200] {local_task_job_runner.py:280} WARNING - Recorded pid 42107 does not match the current pid 41415
[2025-10-10T23:28:39.815+0200] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 41415. PIDs of all processes in the group: [41415]
[2025-10-10T23:28:39.815+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 41415
[2025-10-10T23:29:39.860+0200] {process_utils.py:149} WARNING - process psutil.Process(pid=41415, name='Python', status='running', started='23:27:29') did not respond to SIGTERM. Trying SIGKILL
[2025-10-10T23:29:39.864+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 41415
[2025-10-10T23:29:39.872+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=41415, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='23:27:29') (41415) terminated with exit code Negsignal.SIGKILL
[2025-10-10T23:29:39.872+0200] {standard_task_runner.py:175} ERROR - Job 101 was killed before it finished (likely due to running out of memory)
