[2025-10-10T23:20:18.975+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [queued]>
[2025-10-10T23:20:18.977+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [queued]>
[2025-10-10T23:20:18.977+0200] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-10-10T23:20:18.983+0200] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): send_batch_predictions> on 2025-10-10 21:18:00+00:00
[2025-10-10T23:20:18.988+0200] {standard_task_runner.py:60} INFO - Started process 36680 to run task
[2025-10-10T23:20:18.991+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'predict_batch_dag', 'send_batch_predictions', 'scheduled__2025-10-10T21:18:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/var/folders/rp/syznybx160jd0kg9k7r_sj8w0000gn/T/tmplunc0j2v']
[2025-10-10T23:20:18.992+0200] {standard_task_runner.py:88} INFO - Job 98: Subtask send_batch_predictions
[2025-10-10T23:20:19.012+0200] {task_command.py:423} INFO - Running <TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-10T21:18:00+00:00 [running]> on host ebots-macbook-pro.local
[2025-10-10T23:20:19.033+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='predict_batch_dag' AIRFLOW_CTX_TASK_ID='send_batch_predictions' AIRFLOW_CTX_EXECUTION_DATE='2025-10-10T21:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-10T21:18:00+00:00'
[2025-10-10T23:20:19.033+0200] {logging_mixin.py:188} INFO - ðŸ“„ Found CSV file: /Users/ebotfabien/Desktop/school/air_new/dags/destination/data_part_1.csv
[2025-10-10T23:20:19.042+0200] {logging_mixin.py:188} INFO - ðŸ“¦ Sending 10 batch(es)...
[2025-10-10T23:27:31.900+0200] {local_task_job_runner.py:280} WARNING - Recorded pid 41415 does not match the current pid 36680
[2025-10-10T23:27:31.910+0200] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 36680. PIDs of all processes in the group: [36680]
[2025-10-10T23:27:31.910+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 36680
[2025-10-10T23:28:31.921+0200] {process_utils.py:149} WARNING - process psutil.Process(pid=36680, name='Python', status='running', started='23:20:18') did not respond to SIGTERM. Trying SIGKILL
[2025-10-10T23:28:31.943+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 36680
[2025-10-10T23:28:31.946+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=36680, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='23:20:18') (36680) terminated with exit code Negsignal.SIGKILL
[2025-10-10T23:28:31.948+0200] {standard_task_runner.py:175} ERROR - Job 100 was killed before it finished (likely due to running out of memory)
