[2025-10-11T06:51:26.427+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-11T04:33:10+00:00 [queued]>
[2025-10-11T06:51:26.430+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-11T04:33:10+00:00 [queued]>
[2025-10-11T06:51:26.430+0200] {taskinstance.py:2193} INFO - Starting attempt 5 of 1
[2025-10-11T06:51:26.434+0200] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): send_batch_predictions> on 2025-10-11 04:33:10+00:00
[2025-10-11T06:51:26.437+0200] {standard_task_runner.py:60} INFO - Started process 15037 to run task
[2025-10-11T06:51:26.440+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'predict_batch_dag', 'send_batch_predictions', 'scheduled__2025-10-11T04:33:10+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/prediction_dag.py', '--cfg-path', '/var/folders/rp/syznybx160jd0kg9k7r_sj8w0000gn/T/tmp1eajpbkv']
[2025-10-11T06:51:26.441+0200] {standard_task_runner.py:88} INFO - Job 206: Subtask send_batch_predictions
[2025-10-11T06:52:02.039+0200] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 15037. PIDs of all processes in the group: [15037]
[2025-10-11T06:52:02.040+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 15037
[2025-10-11T06:52:02.042+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=15037, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='06:51:26') (15037) terminated with exit code Negsignal.SIGTERM
[2025-10-11T06:52:25.571+0200] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-11T04:33:10+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-10-11T06:52:25.573+0200] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: predict_batch_dag.send_batch_predictions scheduled__2025-10-11T04:33:10+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-10-11T06:52:25.573+0200] {local_task_job_runner.py:160} INFO - Task is not able to be run
